imx: fix missing "do_mender_tar_src" task
This fix the error about missing task "do_mender_tar_src"

ERROR: Task do_patch in ./meta-mender/meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb depends upon non-existent task do_mender_tar_src in ./meta-imx/meta-bsp/recipes-bsp/u-boot/u-boot-imx_2020.04.bb
ERROR: Command execution failed: 1

Signed-off-by: Clément Péron <peron.clem@gmail.com>