Fix: bootdelay patch for safer application
Failed to consistently apply bootdelay patch:

```
ERROR: u-boot-1_2025.04-r0 do_patch: Applying patch '0001-fix-disable-bootdelay-keypress-detection-on-Pi5-fami.patch' on target directory '[REDACTED]/u-boot/2025.04/git'
...
patching file configs/rpi_arm64_defconfig
Hunk #1 FAILED at 67.
```

This is likely due to conflict with additional automatic U-Boot
configuration completed by the `0001-configs-rpi-enable-mender-requirements.patch`.

Move bootdelay disabling to the top of the defconfig for safer patch
application.

Signed-off-by: Levi Shafter <lshafter@21sw.us>