meta-mender-atmel: bump to dunfell release
Also add meta-openembedded, fixes:

ERROR: Layer 'mender-demo' depends on layer 'openembedded-layer', but this layer is not enabled in your configuration

Changelog: Title

Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>